server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fransasdsa/afk.git # ruta del repositorio git
          searchPaths: config-data

  security:
    user:
      name: root
      password: 123456